"""Editable measurement examples for the desktop interface.

Examples declare measurement conditions, not performance specifications. The
user supplies signal names, windows, target levels and sampling conditions.
"""

CATALOG = [
    ("settling_s", "Settling time", "tran", "s",
     "settle_time(V('out'), start=1u, end=10u, final=1, tol=.01, hold=1u)",
     "Time to enter and remain within 1% of the step. Set the input edge, final level and observation window."),
    ("settling_lsb_s", "Settling to half an LSB", "tran", "s",
     "settle_time(V('out'), start=1u, end=10u, final=1, atol=1/2**13, hold=1u)",
     "Example: 12 bits, 1 V full scale, absolute band ±0.5 LSB. Adjust full scale, resolution and target."),
    ("settled_ok", "Settled flag", "tran", "0/1",
     "settled(V('out'), start=1u, end=10u, final=1, tol=.01, hold=1u)",
     "Use a minimum constraint of 1 when a finite capped settling-time objective is selected."),
    ("settling_error_v", "Settling error", "tran", "V",
     "settling_error(V('out'), start=9u, end=10u, final=1)",
     "Largest absolute error in the chosen observation window. Useful as a smooth optimization target."),
    ("rise_s", "Rise time", "tran", "s",
     "rise_time(V('out'), start=1u, end=10u, initial=0, final=1)",
     "10% to 90% of the specified rising transition; interpolate threshold crossings."),
    ("fall_s", "Fall time", "tran", "s",
     "fall_time(V('out'), start=1u, end=10u, initial=1, final=0)",
     "90% to 10% of the specified falling transition; select one transition window."),
    ("delay_s", "Propagation delay", "tran", "s",
     "delay(V('in'), V('out'), level_x=.5, level_y=.5, start=0, end=10u)",
     "Output crossing minus input crossing. Set edge direction and thresholds for the actual signals."),
    ("slew_v_s", "Slew rate", "tran", "V/s",
     "slew_rate(V('out'), start=1u, end=10u, initial=0, final=1)",
     "Average absolute slope over the 10–90% transition interval."),
    ("overshoot_ratio", "Overshoot", "tran", "V/V",
     "overshoot(V('out'), start=1u, end=10u, initial=0, final=1)",
     "Peak beyond the final level, divided by step amplitude; 0.05 means 5%."),
    ("dc_gain_v_v", "DC gain", "dc", "V/V",
     "dc_gain(V('out'), V('in'), at=0)",
     "Signed local slope at the specified input voltage. Omit at for a fit over the chosen range."),
    ("dc_gain_db", "DC gain in dB", "dc", "dB",
     "db(dc_gain(V('out'), V('in'), at=0))",
     "20 log10 of the magnitude of DC transfer slope; requires a configured DC sweep."),
    ("dc_offset_v", "DC output offset", "dc", "V",
     "dc_offset(V('out'), V('in'))",
     "Intercept of the fitted output-versus-input transfer line; not input-referred offset."),
    ("ripple_vpp", "Peak-to-peak ripple", "tran", "V",
     "pp(V('out'), 9u, 10u)",
     "Maximum minus minimum in the selected settled window."),
    ("noise_rms_v", "RMS deviation", "tran", "V",
     "std(V('out'), 9u, 10u)",
     "Time-weighted RMS after removing the mean. A deterministic trace does not include device noise automatically."),
    ("power_w", "Average supply power", "tran", "W",
     "avg(-V('vdd') * I('VDD'), 1u, 10u)",
     "Supply voltage times delivered source current. Verify the simulator current sign convention."),
    ("energy_j", "Energy per operation", "tran", "J",
     "integ(-V('vdd') * I('VDD'), 1u, 2u)",
     "Integrate delivered supply power over one declared operation window."),
    ("adc_sndr_db", "ADC SNDR / SINAD", "tran", "dB",
     "sndr_fft(V('out'), fs=1M, fund=17, nsamp=1024, t0=10u)",
     "Fundamental versus all non-DC noise and distortion. fund is an FFT bin; use a fixed valid sampling phase."),
    ("adc_snr_db", "ADC SNR", "tran", "dB",
     "snr_fft(V('out'), fs=1M, fund=17, nsamp=1024, t0=10u, harmonics=5)",
     "Exclude DC and harmonics through the specified order; choose coherent sampling or a Hann window."),
    ("adc_thd_db", "ADC THD", "tran", "dBc",
     "thd_fft(V('out'), fs=1M, fund=17, nsamp=1024, t0=10u, harmonics=5)",
     "Harmonic power relative to fundamental; typically negative dBc, with lower values preferred."),
    ("adc_sfdr_db", "ADC SFDR", "tran", "dBc",
     "sfdr_fft(V('out'), fs=1M, fund=17, nsamp=1024, t0=10u)",
     "Fundamental relative to the strongest spur, including harmonic spurs."),
    ("adc_enob", "ADC ENOB", "tran", "bit",
     "enob(V('out'), fs=1M, fund=17, nsamp=1024, t0=10u)",
     "(SNDR − 1.76) / 6.02, using the conventional full-scale sine definition."),
    ("adc_dnl_lsb", "ADC DNL", "tran", "LSB",
     "adc_static(sample(V('code'), fs=1M, nsamp=4096, t0=10u, method='previous'), bits=8, method='histogram')['dnl_peak']",
     "Peak absolute DNL from integer codes under a complete uniform ramp; not a sine-wave histogram."),
    ("adc_inl_lsb", "ADC INL", "tran", "LSB",
     "adc_static(sample(V('code'), fs=1M, nsamp=4096, t0=10u, method='previous'), bits=8, method='histogram')['inl_peak']",
     "Peak absolute code-density INL; full ramp coverage and adequate samples per code are required."),
    ("adc_missing", "ADC missing codes", "tran", "count",
     "len(adc_static(sample(V('code'), fs=1M, nsamp=4096, t0=10u, method='previous'), bits=8, method='histogram')['missing_codes'])",
     "Unobserved codes under a qualified full-range uniform ramp. Insufficient excitation is not proof of missing codes."),
]


def metric_catalog():
    return [dict(zip(("name", "title", "analysis", "unit", "expr", "description"), row))
            for row in CATALOG]
